# Generated by Django 3.2.3 on 2021-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20210525_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
